services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=labelapp'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'

  spring-boot:
    build:
      dockerfile: 'Dockerfile.prod'
    ports:
      - '8080:8080'
    environment:
      - 'spring.datasource.url=jdbc:mysql://mysql:3306/labelapp'
      - 'spring.datasource.username=myuser'
      - 'spring.datasource.password=secret'
    depends_on:
      - 'mysql'