FROM gradle:8.2.1-jdk17-alpine AS builder
ENV APP_HOME=/app
WORKDIR $APP_HOME
COPY build.gradle settings.gradle $APP_HOME
COPY --chown=gradle:gradle . $APP_HOME
RUN gradle build --no-daemon

FROM gradle:8.2.1-jdk17-alpine
ENV APP_HOME=/app
WORKDIR $APP_HOME
EXPOSE 8080
COPY --from=builder $APP_HOME/build/libs/labelapp-0.0.1-SNAPSHOT.jar $APP_HOME/build/libs/labelapp-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/app/build/libs/labelapp-0.0.1-SNAPSHOT.jar" ]